// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBszIOsnlN7v4FtcNBitL-y7rrKZ6J5kwk',
    appId: '1:186870894086:web:66107de8d7045abb853d87',
    messagingSenderId: '186870894086',
    projectId: 'vitalis-3c404',
    authDomain: 'vitalis-3c404.firebaseapp.com',
    storageBucket: 'vitalis-3c404.firebasestorage.app',
    measurementId: 'G-MVHZ5BY5DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvcfwzn-45JyijJeAOVMKQBohma6jJLk',
    appId: '1:186870894086:android:e7be12b1f69f7f2f853d87',
    messagingSenderId: '186870894086',
    projectId: 'vitalis-3c404',
    storageBucket: 'vitalis-3c404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrkCrZuPg4fl7HLEfdYC6ilycWciucm5M',
    appId: '1:186870894086:ios:814546db0747ac5b853d87',
    messagingSenderId: '186870894086',
    projectId: 'vitalis-3c404',
    storageBucket: 'vitalis-3c404.firebasestorage.app',
    iosBundleId: 'com.example.vitalisMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrkCrZuPg4fl7HLEfdYC6ilycWciucm5M',
    appId: '1:186870894086:ios:814546db0747ac5b853d87',
    messagingSenderId: '186870894086',
    projectId: 'vitalis-3c404',
    storageBucket: 'vitalis-3c404.firebasestorage.app',
    iosBundleId: 'com.example.vitalisMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBszIOsnlN7v4FtcNBitL-y7rrKZ6J5kwk',
    appId: '1:186870894086:web:62595e8bf6744543853d87',
    messagingSenderId: '186870894086',
    projectId: 'vitalis-3c404',
    authDomain: 'vitalis-3c404.firebaseapp.com',
    storageBucket: 'vitalis-3c404.firebasestorage.app',
    measurementId: 'G-WEBY6NTZN6',
  );
}
